### ISSUE TITLE
Fix load order and make specs run

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/niso-jats#1]
The load order currently is broken. This task is to fix the load order and then make specs run.

Reproduce by running `bundle console`:

```
NameError: uninitialized constant Niso::Jats::BasicText::RelatedArticle
  lib/niso/jats/basic_text.rb:46:in `included'
          lib/niso/jats/underline.rb:56:in `include'
          lib/niso/jats/underline.rb:56:in `<class:Underline>'
          lib/niso/jats/underline.rb:50:in `<module:Jats>'
          lib/niso/jats/underline.rb:43:in `<module:Niso>'
          lib/niso/jats/underline.rb:42:in `<top (required)>'
          lib/niso/jats/target.rb:19:in `require_relative'
          lib/niso/jats/target.rb:19:in `<top (required)>'
          lib/niso/jats/sup.rb:35:in `require_relative'
          lib/niso/jats/sup.rb:35:in `<top (required)>'
          lib/niso/jats/sub.rb:34:in `require_relative'
          lib/niso/jats/sub.rb:34:in `<top (required)>'
          lib/niso/jats/institution.rb:5:in `require_relative'
          lib/niso/jats/institution.rb:5:in `<top (required)>'
          lib/niso/jats/aff.rb:16:in `require_relative'
          lib/niso/jats/aff.rb:16:in `<top (required)>'
          lib/niso/jats/collab.rb:8:in `require_relative'
          lib/niso/jats/collab.rb:8:in `<top (required)>'
          lib/niso/jats/element_citation.rb:12:in `require_relative'
          lib/niso/jats/element_citation.rb:12:in `<top (required)>'
          lib/niso/jats/citation_alternatives.rb:5:in `require_relative'
          lib/niso/jats/citation_alternatives.rb:5:in `<top (required)>'
          lib/niso/jats/title.rb:10:in `require_relative'
          lib/niso/jats/title.rb:10:in `<top (required)>'
          lib/niso/jats/caption.rb:6:in `require_relative'
          lib/niso/jats/caption.rb:6:in `<top (required)>'
          lib/niso/jats/boxed_text.rb:12:in `require_relative'
          lib/niso/jats/boxed_text.rb:12:in `<top (required)>'
          lib/niso/jats/block_alternatives.rb:5:in `require_relative'
          lib/niso/jats/block_alternatives.rb:5:in `<top (required)>'
          lib/niso/jats/explanation.rb:11:in `require_relative'
          lib/niso/jats/explanation.rb:11:in `<top (required)>'
          lib/niso/jats/answer_set.rb:7:in `require_relative'
          lib/niso/jats/answer_set.rb:7:in `<top (required)>'
          lib/niso/jats/styled_content.rb:9:in `require_relative'
          lib/niso/jats/styled_content.rb:9:in `<top (required)>'
          lib/niso/jats/strike.rb:32:in `require_relative'
          lib/niso/jats/strike.rb:32:in `<top (required)>'
          lib/niso/jats/sc.rb:31:in `require_relative'
          lib/niso/jats/sc.rb:31:in `<top (required)>'
          lib/niso/jats/sans_serif.rb:30:in `require_relative'
          lib/niso/jats/sans_serif.rb:30:in `<top (required)>'
          lib/niso/jats/rb.rb:11:in `require_relative'
          lib/niso/jats/rb.rb:11:in `<top (required)>'
          lib/niso/jats/ruby.rb:5:in `require_relative'
          lib/niso/jats/ruby.rb:5:in `<top (required)>'
          lib/niso/jats/roman.rb:28:in `require_relative'
          lib/niso/jats/roman.rb:28:in `<top (required)>'
          lib/niso/jats/chapter_title.rb:21:in `require_relative'
          lib/niso/jats/chapter_title.rb:21:in `<top (required)>'
          lib/niso/jats/related_object.rb:8:in `require_relative'
          lib/niso/jats/related_object.rb:8:in `<top (required)>'
          lib/niso/jats/basic_text.rb:27:in `require_relative'
          lib/niso/jats/basic_text.rb:27:in `included'
          lib/niso/jats/article_title.rb:14:in `include'
          lib/niso/jats/article_title.rb:14:in `<class:ArticleTitle>'
          lib/niso/jats/article_title.rb:10:in `<module:Jats>'
          lib/niso/jats/article_title.rb:9:in `<module:Niso>'
          lib/niso/jats/article_title.rb:8:in `<top (required)>'
          lib/niso/jats/related_article.rb:6:in `require_relative'
          lib/niso/jats/related_article.rb:6:in `<top (required)>'
          lib/niso/jats/overline.rb:25:in `require_relative'
          lib/niso/jats/overline.rb:25:in `<top (required)>'
          lib/niso/jats/alt_title.rb:25:in `require_relative'
          lib/niso/jats/alt_title.rb:25:in `<top (required)>'
          lib/niso/jats/answer.rb:6:in `require_relative'
          lib/niso/jats/answer.rb:6:in `<top (required)>'
          lib/niso/jats/named_content.rb:8:in `require_relative'
          lib/niso/jats/named_content.rb:8:in `<top (required)>'
          lib/niso/jats/monospace.rb:22:in `require_relative'
          lib/niso/jats/monospace.rb:22:in `<top (required)>'
          lib/niso/jats/inline_supplementary_material.rb:12:in `require_relative'
          lib/niso/jats/inline_supplementary_material.rb:12:in `<top (required)>'
          lib/niso/jats/italic.rb:18:in `require_relative'
          lib/niso/jats/italic.rb:18:in `<top (required)>'
          lib/niso/jats/inline_media.rb:10:in `require_relative'
          lib/niso/jats/inline_media.rb:10:in `<top (required)>'
          lib/niso/jats/inline_formula.rb:11:in `require_relative'
          lib/niso/jats/inline_formula.rb:11:in `<top (required)>'
          lib/niso/jats/label.rb:9:in `require_relative'
          lib/niso/jats/label.rb:9:in `<top (required)>'
          lib/niso/jats/abstract.rb:5:in `require_relative'
          lib/niso/jats/abstract.rb:5:in `<top (required)>'
          lib/niso/jats/disp_formula.rb:5:in `require_relative'
          lib/niso/jats/disp_formula.rb:5:in `<top (required)>'
          lib/niso/jats/see.rb:11:in `require_relative'
          lib/niso/jats/see.rb:11:in `<top (required)>'
          lib/niso/jats/index_term.rb:5:in `require_relative'
          lib/niso/jats/index_term.rb:5:in `<top (required)>'
          lib/niso/jats/fixed_case.rb:12:in `require_relative'
          lib/niso/jats/fixed_case.rb:12:in `<top (required)>'
          lib/niso/jats/ext_link.rb:6:in `require_relative'
          lib/niso/jats/ext_link.rb:6:in `<top (required)>'
          lib/niso/jats/code.rb:8:in `require_relative'
          lib/niso/jats/code.rb:8:in `<top (required)>'
          lib/niso/jats/chem_struct.rb:10:in `require_relative'
          lib/niso/jats/chem_struct.rb:10:in `<top (required)>'
          lib/niso/jats/attrib.rb:8:in `require_relative'
          lib/niso/jats/attrib.rb:8:in `<top (required)>'
          lib/niso/jats/array.rb:7:in `require_relative'
          lib/niso/jats/array.rb:7:in `<top (required)>'
          lib/niso/jats/alternatives.rb:5:in `require_relative'
          lib/niso/jats/alternatives.rb:5:in `<top (required)>'
          lib/niso/jats/addr_line.rb:6:in `require_relative'
          lib/niso/jats/addr_line.rb:6:in `<top (required)>'
          lib/niso/jats/address.rb:5:in `require_relative'
          lib/niso/jats/address.rb:5:in `<top (required)>'
          lib/niso/jats/paragraph.rb:6:in `require_relative'
          lib/niso/jats/paragraph.rb:6:in `<top (required)>'
          lib/niso/jats/def.rb:5:in `require_relative'
          lib/niso/jats/def.rb:5:in `<top (required)>'
          lib/niso/jats/abbrev.rb:5:in `require_relative'
          lib/niso/jats/abbrev.rb:5:in `<top (required)>'
          lib/niso/jats/bold.rb:5:in `require_relative'
          lib/niso/jats/bold.rb:5:in `<top (required)>'
          lib/niso/jats/std.rb:5:in `require_relative'
          lib/niso/jats/std.rb:5:in `<top (required)>'
          lib/niso/jats.rb:19:in `require_relative'
          lib/niso/jats.rb:19:in `<top (required)>'
```

**Comment by zznull** [comment]
@ronaldtse is there a reason for using `require_relative` everywhere?

**Comment by zznull** [comment]
I have fixed the loading, specs are running but 5/6 of them are failing because of xml differences. Does the $100 bounty apply only to fixing loading or also fixing the functionality?

**Comment by dmytro-strukov** [comment]
@zznull I think the big advantage of `require_relative` is better performance compared with `require` because it will not look up in all $LOAD_PATH directories. 

Your approach with lazy `autoload` (legacy method) can break Threads in Ruby and be the reason for race conditions.

https://bugs.ruby-lang.org/issues/5653

P.S. Also your solution does not describe root cause of the error

**Comment by zznull** [comment]
@dmytro-strukov thanks for pointing that out. I closed the PR.

**Comment by dmytro-strukov** [comment]
@ronaldtse After reviewing the code and analyzing the issue, I have identified the following problem:

- The management of dependencies is suboptimal. Each file contains numerous require_relative statements. I strongly recommend consolidating these into a single entry point, such as `lib/niso/jats.rb`.
- This approach increases the risk of circular dependencies in Ruby, and I am confident that this is the case here.

**Comment by Novtopro** [comment]
@ronaldtse I agree with @dmytro-strukov, the root cause is circular dependencies introduced by numerous `require_relative` statements. We can make use `autoload` to simplify the dependency management for this gem without introducing other tools or libs.

Please review my PR https://github.com/metanorma/niso-jats/pull/5 and run the pipeline. I've skipped one of the tests since it's not relevant to the issue we're focusing on. It will take more time to figure out the reason why the test fails since we need to know more about what the gem is doing.

**Comment by Novtopro** [comment]
@ronaldtse Updated my PR. Added missing gem and fixed lint errors.

**Comment by Novtopro** [comment]
@ronaldtse Just realized that the `autoload` is not recommended anymore, I've updated my PR to use `zeitwerk` as the code loader.

**Comment by zznull** [comment]
@Novtopro did you see #4 ?

**Comment by Novtopro** [comment]
@zznull Ah, just saw it and left a comment. But I still would suggest handling the code loader like https://github.com/metanorma/niso-jats/pull/5/commits/7f04be62c32f9e0eb323f711f34ede6418a4f562
@ronaldtse What do you think?

**Comment by Novtopro** [comment]
@ronaldtse 
![CleanShot 2024-10-25 at 19 32 50@2x](https://github.com/user-attachments/assets/b3c6e7d4-6c4f-4b4c-bef3-69462041c168)
https://github.com/metanorma/niso-jats/actions/runs/11514184090/job/32060408756

**Comment by ronaldtse** [comment]
Done in #6. The specs now run properly thanks to @valter0ff. @Novtopro previously due to the commented out spec it was hiding the fact that BasicText wasn't included prior to being called in the spec. Thank you everyone!

**Comment by Novtopro** [comment]
@ronaldtse So who will get the $100 bounty? I think @zznull, @valterOff would like to know your rules about your post in Upwork as well. Could you please clarify?

**Comment by ronaldtse** [comment]
@zznull thank you for suggesting Zeitwerk for this gem!

@Novtopro @valter0ff I have communicated to you offline, thanks.
